using System;

namespace MerchantRPG.Data
{
	public static class Library
	{
		public static Hero[] Heroes = new Hero[] {
			new Hero("Warrior", 5, 1, 4, 
				100, 5, 1, 2, 1, 14, 8, 
				10, 0.4, 0.1, 0.3, 0, 1, 0.4),
			new Hero("Rogue", 4, 1, 5, 
				90, 5, 1, 2, 5, 9, 8, 
				8, 0.6, 0.1, 0.5, 0.2, 0.5, 0.4),
			new Hero("Mage", 1, 6, 3, 
				80, 1, 5, 2, 1, 7, 10, 
				7, 0.1, 0.9, 0.3, 0, 0.4, 0.4),
			new Hero("Berserker", 6, 1, 3, 
				90, 5, 1, 2, 1, 10, 7, 
				8, 0.8, 0.1, 0.3, 0, 0.5, 0.4),
			new Hero("Cleric", 1, 5, 4, 
				80, 1, 5, 2, 1, 7, 10, 
				7, 0.1, 0.6, 0.6, 0, 0.4, 0.4),
			new Hero("Assassin", 3, 1, 6, 
				90, 5, 1, 2, 10, 9, 8, 
				8, 0.4, 0.1, 0.7, 0.2, 0.5, 0.4),
			new Hero("Paladin", 4, 4, 2, 
				100, 3, 3, 2, 1, 8, 14, 
				10, 0.3, 0.3, 0.3, 0, 0.4, 1),
			new Hero("Dark Knight", 5, 5, 0, 
				80, 3, 3, 2, 1, 9, 8, 
				7, 0.45, 0.55, 0.3, 0, 0.4, 0.4),
		};
		
		public static ItemTemplate[] Blacksmith = {
			new ItemTemplate("Oni's Decapitator", 40, ItemSlot.Weapon, ItemParts.LongswordStereotype, criticalRate: 15, strength: 7, hp: -30),
			new ItemTemplate("Leviathan's Bite", 20, ItemSlot.Weapon, ItemParts.DaggerStereotype, magicAttack: 7, strength: 3, dexterity: 3),
			new ItemTemplate("King's Blade", 39, ItemSlot.Weapon, ItemParts.LongswordStereotype, magicAttack: 9, accuracy: 9, strength: 6),
			new ItemTemplate("Undead Axe", 38, ItemSlot.Weapon, ItemParts.AxeStereotype, strength: 5, hp: -20),
			new ItemTemplate("Undead Longsword", 37, ItemSlot.Weapon, ItemParts.LongswordStereotype, strength: 5, hp: -20),
			new ItemTemplate("Undead Knife", 36, ItemSlot.Weapon, ItemParts.KnifeStereotype, strength: 5, hp: -20),
			new ItemTemplate("Beast Hatchet", 37, ItemSlot.Weapon, ItemParts.HatchetStereotype, dexterity: 3, hp: 25),
			new ItemTemplate("Beast Sword", 36, ItemSlot.Weapon, ItemParts.SwordStereotype, dexterity: 3, hp: 25),
			new ItemTemplate("Darksteel Axe", 35, ItemSlot.Weapon, ItemParts.AxeStereotype),
			new ItemTemplate("Darksteel Longsword", 34, ItemSlot.Weapon, ItemParts.LongswordStereotype),
			new ItemTemplate("Darksteel Knife", 33, ItemSlot.Weapon, ItemParts.KnifeStereotype),
			new ItemTemplate("Darksteel Hatchet", 33, ItemSlot.Weapon, ItemParts.HatchetStereotype),
			new ItemTemplate("Darksteel Sword", 32, ItemSlot.Weapon, ItemParts.SwordStereotype),
			new ItemTemplate("Darksteel Dagger", 31, ItemSlot.Weapon, ItemParts.DaggerStereotype),
			new ItemTemplate("Battlelord's Blade", 29, ItemSlot.Weapon, ItemParts.LongswordStereotype, attack: 7, accuracy: 7, strength: 5),
			new ItemTemplate("Overlord's Battleaxe", 29, ItemSlot.Weapon, ItemParts.AxeStereotype, criticalRate: 7, strength: 4),
			new ItemTemplate("Ceros' Knife", 28, ItemSlot.Weapon, ItemParts.KnifeStereotype, defense: 7, strength: 4),
			new ItemTemplate("Gnoll Axe", 28, ItemSlot.Weapon, ItemParts.AxeStereotype, attack: 5, dexterity: 3),
			new ItemTemplate("Gnoll Longsword", 27, ItemSlot.Weapon, ItemParts.LongswordStereotype, attack: 5, dexterity: 3),
			new ItemTemplate("Ram Hatchet", 27, ItemSlot.Weapon, ItemParts.HatchetStereotype, attack: 5, defense: 5),
			new ItemTemplate("Gnoll Knife", 26, ItemSlot.Weapon, ItemParts.KnifeStereotype, attack: 5, dexterity: 3),
			new ItemTemplate("Ram Sword", 26, ItemSlot.Weapon, ItemParts.SwordStereotype, attack: 5, defense: 5),
			new ItemTemplate("Adaman Axe", 25, ItemSlot.Weapon, ItemParts.AxeStereotype),
			new ItemTemplate("Adaman Longsword", 24, ItemSlot.Weapon, ItemParts.LongswordStereotype),
			new ItemTemplate("Adaman Knife", 23, ItemSlot.Weapon, ItemParts.KnifeStereotype),
			new ItemTemplate("Adaman Hatchet", 23, ItemSlot.Weapon, ItemParts.HatchetStereotype),
			new ItemTemplate("Adaman Sword", 22, ItemSlot.Weapon, ItemParts.SwordStereotype),
			new ItemTemplate("Adaman Dagger", 21, ItemSlot.Weapon, ItemParts.DaggerStereotype),
			new ItemTemplate("Prime Battleaxe", 19, ItemSlot.Weapon, ItemParts.AxeStereotype, criticalRate: 5, strength: 3),
			new ItemTemplate("Basamus' Sword", 18, ItemSlot.Weapon, ItemParts.SwordStereotype, strength: 3),
			new ItemTemplate("Thief's Knife", 18, ItemSlot.Weapon, ItemParts.KnifeStereotype),
			new ItemTemplate("Murlok Axe", 18, ItemSlot.Weapon, ItemParts.AxeStereotype, accuracy: 5),
			new ItemTemplate("Water Spellsword", 17, ItemSlot.Weapon, ItemParts.LongswordStereotype, magicAttack: 5),
			new ItemTemplate("Lizard Hatchet", 17, ItemSlot.Weapon, ItemParts.HatchetStereotype, attack: 5),
			new ItemTemplate("Murlok Longsword", 17, ItemSlot.Weapon, ItemParts.LongswordStereotype, accuracy: 5),
			new ItemTemplate("Murlok Knife", 16, ItemSlot.Weapon, ItemParts.KnifeStereotype, accuracy: 5),
			new ItemTemplate("Lizard Dagger", 15, ItemSlot.Weapon, ItemParts.DaggerStereotype, attack: 5),
			new ItemTemplate("Turtle Sword", 15, ItemSlot.Weapon, ItemParts.SwordStereotype, hp: 12),
			new ItemTemplate("Mithril Axe", 15, ItemSlot.Weapon, ItemParts.AxeStereotype),
			new ItemTemplate("Mithril Longsword", 14, ItemSlot.Weapon, ItemParts.LongswordStereotype),
			new ItemTemplate("Mithril Knife", 13, ItemSlot.Weapon, ItemParts.KnifeStereotype),
			new ItemTemplate("Mithril Hatchet", 13, ItemSlot.Weapon, ItemParts.HatchetStereotype),
			new ItemTemplate("Mithril Sword", 12, ItemSlot.Weapon, ItemParts.SwordStereotype),
			new ItemTemplate("Mithril Dagger", 11, ItemSlot.Weapon, ItemParts.DaggerStereotype),
			new ItemTemplate("Bloody Axe", 9, ItemSlot.Weapon, ItemParts.AxeStereotype, accuracy: 3, strength: 1),
			new ItemTemplate("Chieftain's Longsword", 8, ItemSlot.Weapon, ItemParts.LongswordStereotype, strength: 1),
			new ItemTemplate("Venom's Knife", 8, ItemSlot.Weapon, ItemParts.KnifeStereotype, magicAttack: 3, dexterity: 1),
			new ItemTemplate("Goblin Hatchet", 7, ItemSlot.Weapon, ItemParts.HatchetStereotype, attack: 3),
			new ItemTemplate("Goblin Sword", 6, ItemSlot.Weapon, ItemParts.SwordStereotype, attack: 3),
			new ItemTemplate("Fang Hatchet", 6, ItemSlot.Weapon, ItemParts.HatchetStereotype, criticalRate: 3),
			new ItemTemplate("Boar Sword", 5, ItemSlot.Weapon, ItemParts.SwordStereotype, defense: 3),
			new ItemTemplate("Fang Knife", 5, ItemSlot.Weapon, ItemParts.KnifeStereotype, criticalRate: 3),
			new ItemTemplate("Iron Axe", 5, ItemSlot.Weapon, ItemParts.AxeStereotype),
			new ItemTemplate("Iron Longsword", 4, ItemSlot.Weapon, ItemParts.LongswordStereotype),
			new ItemTemplate("Iron Knife", 3, ItemSlot.Weapon, ItemParts.KnifeStereotype),
			new ItemTemplate("Iron Hatchet", 3, ItemSlot.Weapon, ItemParts.HatchetStereotype),
			new ItemTemplate("Iron Sword", 2, ItemSlot.Weapon, ItemParts.SwordStereotype),
			new ItemTemplate("Iron Dagger", 1, ItemSlot.Weapon, ItemParts.DaggerStereotype),
		};

		public static ItemTemplate[] Armorsmith = {
			new ItemTemplate("King's Guard", 39, ItemSlot.Chest, ItemParts.PlatemailStereotype, defense: 10, strength: 5, hp: 30),
			new ItemTemplate("Arthus' Gauntlets", 39, ItemSlot.Gloves, ItemParts.GauntletsStereotype, magicDefense: 7, attack: 7, strength: 4),
			new ItemTemplate("Serket's Treads", 39, ItemSlot.Boots, ItemParts.BootsStereotype, magicAttack: 7, strength: 3, dexterity: 3),
			new ItemTemplate("Undead Chainmail", 38, ItemSlot.Chest, ItemParts.ChainmailStereotype, accuracy: -5, criticalRate: 7, strength: 5),
			new ItemTemplate("Undead Helm", 37, ItemSlot.Helm, ItemParts.HelmStereotype, accuracy: -4, criticalRate: 5, strength: 4),
			new ItemTemplate("Undead Greaves", 36, ItemSlot.Boots, ItemParts.GreavesStereotype, accuracy: -3, criticalRate: 3, strength: 3),
			new ItemTemplate("Undead Bracers", 36, ItemSlot.Gloves, ItemParts.BracersStereotype, accuracy: -3, criticalRate: 3, strength: 3),
			new ItemTemplate("Scorpion Platemail", 37, ItemSlot.Chest, ItemParts.PlatemailStereotype, magicAttack: 7, strength: 4),
			new ItemTemplate("Scorpion Great Helm", 36, ItemSlot.Helm, ItemParts.GreatHelmStereotype, magicAttack: 7, strength: 3),
			new ItemTemplate("Darksteel Platemail", 36, ItemSlot.Chest, ItemParts.PlatemailStereotype),
			new ItemTemplate("Scorpion Sabatons", 35, ItemSlot.Boots, ItemParts.SabatonsStereotype, magicAttack: 5, strength: 2),
			new ItemTemplate("Scorpion Gauntlets", 35, ItemSlot.Gloves, ItemParts.GauntletsStereotype, magicAttack: 5, strength: 2),
			new ItemTemplate("Darksteel Great Helm", 35, ItemSlot.Helm, ItemParts.GreatHelmStereotype),
			new ItemTemplate("Darksteel Sabatons", 34, ItemSlot.Boots, ItemParts.SabatonsStereotype),
			new ItemTemplate("Darksteel Gauntlets", 34, ItemSlot.Gloves, ItemParts.GauntletsStereotype),
			new ItemTemplate("Darksteel Chainmail", 33, ItemSlot.Chest, ItemParts.ChainmailStereotype),
			new ItemTemplate("Darksteel Helm", 32, ItemSlot.Helm, ItemParts.HelmStereotype),
			new ItemTemplate("Darksteel Greaves", 31, ItemSlot.Boots, ItemParts.GreavesStereotype),
			new ItemTemplate("Darksteel Bracers", 31, ItemSlot.Gloves, ItemParts.BracersStereotype),
			new ItemTemplate("Ares' Helm", 29, ItemSlot.Helm, ItemParts.HelmStereotype, defense: 5, attack: 5, strength: 4),
			new ItemTemplate("Ares' Bracers", 29, ItemSlot.Gloves, ItemParts.BracersStereotype, defense: 7, strength: 2),
			new ItemTemplate("Gnoll Chainmail", 29, ItemSlot.Chest, ItemParts.ChainmailStereotype, criticalRate: 4, strength: 3),
			new ItemTemplate("Fighters Greaves", 28, ItemSlot.Boots, ItemParts.GreavesStereotype, strength: 2, dexterity: 2),
			new ItemTemplate("Gnoll Helm", 28, ItemSlot.Helm, ItemParts.HelmStereotype, criticalRate: 4, strength: 2),
			new ItemTemplate("Gnoll Platemail", 28, ItemSlot.Chest, ItemParts.PlatemailStereotype, attack: 5, dexterity: 3),
			new ItemTemplate("Gnoll Greaves", 27, ItemSlot.Boots, ItemParts.GreavesStereotype, criticalRate: 3, strength: 1),
			new ItemTemplate("Gnoll Bracers", 27, ItemSlot.Gloves, ItemParts.BracersStereotype, criticalRate: 3, strength: 1),
			new ItemTemplate("Gnoll Great Helm", 27, ItemSlot.Helm, ItemParts.GreatHelmStereotype, attack: 4, dexterity: 2),
			new ItemTemplate("Ram Chainmail", 27, ItemSlot.Chest, ItemParts.ChainmailStereotype, defense: 5, attack: 5),
			new ItemTemplate("Gnoll Sabatons", 26, ItemSlot.Boots, ItemParts.SabatonsStereotype, attack: 3, dexterity: 1),
			new ItemTemplate("Gnoll Gauntlets", 26, ItemSlot.Gloves, ItemParts.GauntletsStereotype, attack: 3, dexterity: 1),
			new ItemTemplate("Adaman Platemail", 26, ItemSlot.Chest, ItemParts.PlatemailStereotype),
			new ItemTemplate("Ram Helm", 26, ItemSlot.Helm, ItemParts.HelmStereotype, defense: 4, attack: 4),
			new ItemTemplate("Ram Greaves", 25, ItemSlot.Boots, ItemParts.GreavesStereotype, defense: 3, attack: 3),
			new ItemTemplate("Ram Bracers", 25, ItemSlot.Gloves, ItemParts.BracersStereotype, defense: 3, attack: 3),
			new ItemTemplate("Adaman Great Helm", 25, ItemSlot.Helm, ItemParts.GreatHelmStereotype),
			new ItemTemplate("Adaman Sabatons", 24, ItemSlot.Boots, ItemParts.SabatonsStereotype),
			new ItemTemplate("Adaman Gauntlets", 24, ItemSlot.Gloves, ItemParts.GauntletsStereotype),
			new ItemTemplate("Adaman Chainmail", 23, ItemSlot.Chest, ItemParts.ChainmailStereotype),
			new ItemTemplate("Adaman Helm", 22, ItemSlot.Helm, ItemParts.HelmStereotype),
			new ItemTemplate("Adaman Greaves", 21, ItemSlot.Boots, ItemParts.GreavesStereotype),
			new ItemTemplate("Adaman Bracers", 21, ItemSlot.Gloves, ItemParts.BracersStereotype),
			new ItemTemplate("Shellmail", 19, ItemSlot.Chest, ItemParts.PlatemailStereotype, defense: 4, magicDefense: 4, hp: 15),
			new ItemTemplate("Warleader's Gauntlets", 18, ItemSlot.Gloves, ItemParts.GauntletsStereotype, attack: 4, strength: 2),
			new ItemTemplate("Murlok Chainmail", 18, ItemSlot.Chest, ItemParts.ChainmailStereotype, dexterity: 2),
			new ItemTemplate("Assault Helm", 18, ItemSlot.Helm, ItemParts.HelmStereotype, attack: 4, accuracy: 4),
			new ItemTemplate("Turtle Platemail", 17, ItemSlot.Chest, ItemParts.PlatemailStereotype, hp: 15),
			new ItemTemplate("Murlok Helm", 17, ItemSlot.Helm, ItemParts.HelmStereotype, accuracy: 5),
			new ItemTemplate("Heavy Greaves", 17, ItemSlot.Boots, ItemParts.GreavesStereotype, magicDefense: 4),
			new ItemTemplate("Heavy Bracers", 17, ItemSlot.Gloves, ItemParts.BracersStereotype, magicDefense: 4),
			new ItemTemplate("Turtle Great Helm", 16, ItemSlot.Helm, ItemParts.GreatHelmStereotype, hp: 12),
			new ItemTemplate("Lizard Greaves", 16, ItemSlot.Boots, ItemParts.GreavesStereotype, attack: 4),
			new ItemTemplate("Lizard Bracers", 16, ItemSlot.Gloves, ItemParts.BracersStereotype, attack: 4),
			new ItemTemplate("Mithril Platemail", 16, ItemSlot.Chest, ItemParts.PlatemailStereotype),
			new ItemTemplate("Turtle Sabatons", 15, ItemSlot.Boots, ItemParts.SabatonsStereotype, hp: 7),
			new ItemTemplate("Turtle Gauntlets", 15, ItemSlot.Gloves, ItemParts.GauntletsStereotype, hp: 7),
			new ItemTemplate("Mithril Great Helm", 15, ItemSlot.Helm, ItemParts.GreatHelmStereotype),
			new ItemTemplate("Mithril Sabatons", 14, ItemSlot.Boots, ItemParts.SabatonsStereotype),
			new ItemTemplate("Mithril Gauntlets", 14, ItemSlot.Gloves, ItemParts.GauntletsStereotype),
			new ItemTemplate("Mithril Chainmail", 13, ItemSlot.Chest, ItemParts.ChainmailStereotype),
			new ItemTemplate("Mithril Helm", 12, ItemSlot.Helm, ItemParts.HelmStereotype),
			new ItemTemplate("Mithril Greaves", 11, ItemSlot.Boots, ItemParts.GreavesStereotype),
			new ItemTemplate("Mithril Bracers", 11, ItemSlot.Gloves, ItemParts.BracersStereotype),
			new ItemTemplate("Gronok's Platemail", 9, ItemSlot.Chest, ItemParts.PlatemailStereotype, strength: 1, hp: 7),
			new ItemTemplate("Goblin Platemail", 8, ItemSlot.Chest, ItemParts.PlatemailStereotype, hp: 10),
			new ItemTemplate("Enchanted Helm", 8, ItemSlot.Helm, ItemParts.HelmStereotype, magicDefense: 4),
			new ItemTemplate("Hogger's Bracers", 7, ItemSlot.Gloves, ItemParts.BracersStereotype, attack: 5),
			new ItemTemplate("Goblin Great Helm", 7, ItemSlot.Helm, ItemParts.GreatHelmStereotype, hp: 7),
			new ItemTemplate("Boar Chainmail", 7, ItemSlot.Chest, ItemParts.ChainmailStereotype, defense: 4),
			new ItemTemplate("Goblin Sabatons", 6, ItemSlot.Boots, ItemParts.SabatonsStereotype, hp: 4),
			new ItemTemplate("Goblin Gauntlets", 6, ItemSlot.Gloves, ItemParts.GauntletsStereotype, hp: 4),
			new ItemTemplate("Boar Helm", 6, ItemSlot.Helm, ItemParts.HelmStereotype, defense: 3),
			new ItemTemplate("Iron Platemail", 6, ItemSlot.Chest, ItemParts.PlatemailStereotype),
			new ItemTemplate("Boar Greaves", 5, ItemSlot.Boots, ItemParts.GreavesStereotype, defense: 2),
			new ItemTemplate("Boar Bracers", 5, ItemSlot.Gloves, ItemParts.BracersStereotype, defense: 2),
			new ItemTemplate("Scale Greaves", 5, ItemSlot.Boots, ItemParts.GreavesStereotype, attack: 2),
			new ItemTemplate("Scale Bracers", 5, ItemSlot.Gloves, ItemParts.BracersStereotype, attack: 2),
			new ItemTemplate("Iron Great Helm", 5, ItemSlot.Helm, ItemParts.GreatHelmStereotype),
			new ItemTemplate("Iron Sabatons", 4, ItemSlot.Boots, ItemParts.SabatonsStereotype),
			new ItemTemplate("Iron Gauntlets", 4, ItemSlot.Gloves, ItemParts.GauntletsStereotype),
			new ItemTemplate("Iron Chainmail", 3, ItemSlot.Chest, ItemParts.ChainmailStereotype),
			new ItemTemplate("Iron Helm", 2, ItemSlot.Helm, ItemParts.HelmStereotype),
			new ItemTemplate("Iron Greaves", 1, ItemSlot.Boots, ItemParts.GreavesStereotype),
			new ItemTemplate("Iron Bracers", 1, ItemSlot.Gloves, ItemParts.BracersStereotype),
		};

		public static ItemTemplate[] Woodworker = {
			new ItemTemplate("Hel's Scythe", 40, ItemSlot.Weapon, ItemParts.ScytheStereotype, attack: 15, criticalRate: 7, intelligence: 5),
			new ItemTemplate("Kirin's Wand", 30, ItemSlot.Weapon, ItemParts.WandStereotype, intelligence: 4, dexterity: 4),
			new ItemTemplate("Antares' Stinger", 39, ItemSlot.Weapon, ItemParts.WandStereotype, criticalRate: 7, intelligence: 6, hp: 30),
			new ItemTemplate("Undead Mystic Stave", 38, ItemSlot.Weapon, ItemParts.MysticStaveStereotype, intelligence: 5, hp: -20),
			new ItemTemplate("Undead Cudgel", 37, ItemSlot.Weapon, ItemParts.CudgelStereotype, intelligence: 5, hp: -20),
			new ItemTemplate("Undead Mystic Wand", 36, ItemSlot.Weapon, ItemParts.MysticWandStereotype, intelligence: 5, hp: -20),
			new ItemTemplate("Scorpion Cudgel", 37, ItemSlot.Weapon, ItemParts.CudgelStereotype, attack: 7, intelligence: 3),
			new ItemTemplate("Scorpion Wand", 36, ItemSlot.Weapon, ItemParts.WandStereotype, attack: 7, intelligence: 3),
			new ItemTemplate("Deadwood Mystic Stave", 35, ItemSlot.Weapon, ItemParts.MysticStaveStereotype),
			new ItemTemplate("Deadwood Cudgel", 34, ItemSlot.Weapon, ItemParts.CudgelStereotype),
			new ItemTemplate("Deadwood Mystic Wand", 33, ItemSlot.Weapon, ItemParts.MysticWandStereotype),
			new ItemTemplate("Deadwood Stave", 33, ItemSlot.Weapon, ItemParts.StaveStereotype),
			new ItemTemplate("Deadwood Club", 32, ItemSlot.Weapon, ItemParts.ClubStereotype),
			new ItemTemplate("Deadwood Wand", 31, ItemSlot.Weapon, ItemParts.WandStereotype),
			new ItemTemplate("Ares' Stave", 29, ItemSlot.Weapon, ItemParts.StaveStereotype, defense: 7, intelligence: 4, dexterity: 4),
			new ItemTemplate("Overlord's Cudgel", 29, ItemSlot.Weapon, ItemParts.CudgelStereotype, strength: 4, intelligence: 4),
			new ItemTemplate("Terros' Wand", 28, ItemSlot.Weapon, ItemParts.WandStereotype, intelligence: 3, dexterity: 3),
			new ItemTemplate("Gnoll Mystic Stave", 28, ItemSlot.Weapon, ItemParts.MysticStaveStereotype, intelligence: 2, hp: 15),
			new ItemTemplate("Gnoll Cudgel", 27, ItemSlot.Weapon, ItemParts.CudgelStereotype, intelligence: 2, hp: 15),
			new ItemTemplate("Worm Stave", 27, ItemSlot.Weapon, ItemParts.StaveStereotype, magicAttack: 5, accuracy: 5),
			new ItemTemplate("Gnoll Mystic Wand", 26, ItemSlot.Weapon, ItemParts.MysticWandStereotype, intelligence: 2, hp: 15),
			new ItemTemplate("Worm Wand", 25, ItemSlot.Weapon, ItemParts.WandStereotype, magicAttack: 5, accuracy: 5),
			new ItemTemplate("Oak Mystic Stave", 25, ItemSlot.Weapon, ItemParts.MysticStaveStereotype),
			new ItemTemplate("Oak Cudgel", 24, ItemSlot.Weapon, ItemParts.CudgelStereotype),
			new ItemTemplate("Oak Mystic Wand", 23, ItemSlot.Weapon, ItemParts.MysticWandStereotype),
			new ItemTemplate("Oak Stave", 23, ItemSlot.Weapon, ItemParts.StaveStereotype),
			new ItemTemplate("Oak Club", 22, ItemSlot.Weapon, ItemParts.ClubStereotype),
			new ItemTemplate("Oak Wand", 21, ItemSlot.Weapon, ItemParts.WandStereotype),
			new ItemTemplate("Demolisher's Mace", 19, ItemSlot.Weapon, ItemParts.CudgelStereotype, strength: 3, intelligence: 3),
			new ItemTemplate("Priest's Stave", 19, ItemSlot.Weapon, ItemParts.StaveStereotype, accuracy: 5, intelligence: 3),
			new ItemTemplate("Tidecaller's Wand", 18, ItemSlot.Weapon, ItemParts.WandStereotype, intelligence: 2, hp: 12),
			new ItemTemplate("Murlok Pole", 18, ItemSlot.Weapon, ItemParts.StaveStereotype, accuracy: 5),
			new ItemTemplate("Lizard Cudgel", 17, ItemSlot.Weapon, ItemParts.CudgelStereotype, attack: 5),
			new ItemTemplate("Murlok Rod", 17, ItemSlot.Weapon, ItemParts.ClubStereotype, accuracy: 5),
			new ItemTemplate("Murlok Mystic Stave", 17, ItemSlot.Weapon, ItemParts.MysticStaveStereotype, magicAttack: 5),
			new ItemTemplate("Murlok Club", 16, ItemSlot.Weapon, ItemParts.ClubStereotype, magicAttack: 5),
			new ItemTemplate("Murlok Mystic Wand", 15, ItemSlot.Weapon, ItemParts.MysticWandStereotype, magicAttack: 5),
			new ItemTemplate("Turtle Club", 15, ItemSlot.Weapon, ItemParts.ClubStereotype, hp: 12),
			new ItemTemplate("Willow Mystic Stave", 15, ItemSlot.Weapon, ItemParts.MysticStaveStereotype),
			new ItemTemplate("Willow Cudgel", 14, ItemSlot.Weapon, ItemParts.CudgelStereotype),
			new ItemTemplate("Willow Mystic Wand", 13, ItemSlot.Weapon, ItemParts.MysticWandStereotype),
			new ItemTemplate("Willow Stave", 13, ItemSlot.Weapon, ItemParts.StaveStereotype),
			new ItemTemplate("Willow Club", 12, ItemSlot.Weapon, ItemParts.ClubStereotype),
			new ItemTemplate("Willow Wand", 11, ItemSlot.Weapon, ItemParts.WandStereotype),
			new ItemTemplate("Bloody Club", 9, ItemSlot.Weapon, ItemParts.ClubStereotype, accuracy: 3, intelligence: 1),
			new ItemTemplate("Maexna's Mystic Wand", 8, ItemSlot.Weapon, ItemParts.MysticWandStereotype, intelligence: 1),
			new ItemTemplate("Goblin Mystic Stave", 8, ItemSlot.Weapon, ItemParts.MysticStaveStereotype, magicAttack: 3),
			new ItemTemplate("Goblin Cudgel", 7, ItemSlot.Weapon, ItemParts.CudgelStereotype, attack: 2, magicAttack: 2),
			new ItemTemplate("Spider Stave", 7, ItemSlot.Weapon, ItemParts.StaveStereotype, accuracy: 3),
			new ItemTemplate("Goblin Wand", 6, ItemSlot.Weapon, ItemParts.WandStereotype, magicAttack: 3),
			new ItemTemplate("Boar Club", 6, ItemSlot.Weapon, ItemParts.ClubStereotype, defense: 3),
			new ItemTemplate("Spider Wand", 5, ItemSlot.Weapon, ItemParts.WandStereotype, accuracy: 3),
			new ItemTemplate("Ashe Mystic Stave", 5, ItemSlot.Weapon, ItemParts.MysticStaveStereotype),
			new ItemTemplate("Ashe Cudgel", 4, ItemSlot.Weapon, ItemParts.CudgelStereotype),
			new ItemTemplate("Ashe Mystic Wand", 3, ItemSlot.Weapon, ItemParts.MysticWandStereotype),
			new ItemTemplate("Ashe Stave", 3, ItemSlot.Weapon, ItemParts.StaveStereotype),
			new ItemTemplate("Ashe Club", 2, ItemSlot.Weapon, ItemParts.ClubStereotype),
			new ItemTemplate("Ashe Wand", 1, ItemSlot.Weapon, ItemParts.WandStereotype),
		};

		public static ItemTemplate[] Clothworker = {
			new ItemTemplate("Hel's Robe", 40, ItemSlot.Chest, ItemParts.RobeStereotype, magicDefense: 10, intelligence: 5, hp: 40),
			new ItemTemplate("Oni's Mask", 40, ItemSlot.Helm, ItemParts.HoodStereotype, attack: 10, strength: 4, dexterity: 4),
			new ItemTemplate("Kirin's Sune-Ate", 30, ItemSlot.Boots, ItemParts.BootsStereotype, strength: 2, intelligence: 4, dexterity: 3),
			new ItemTemplate("Kirin's Kote", 30, ItemSlot.Gloves, ItemParts.GlovesStereotype, strength: 4, intelligence: 2, dexterity: 3),
			new ItemTemplate("Leviathan's Doublet", 20, ItemSlot.Chest, ItemParts.TunicStereotype, magicDefense: 5, strength: 3, dexterity: 3),
			new ItemTemplate("Shadow Robe", 39, ItemSlot.Chest, ItemParts.RobeStereotype, intelligence: 5, dexterity: 5),
			new ItemTemplate("Altor's Sandals", 39, ItemSlot.Boots, ItemParts.CrakowsStereotype, magicAttack: 5, accuracy: 5, intelligence: 4),
			new ItemTemplate("Undead Robe", 39, ItemSlot.Chest, ItemParts.RobeStereotype, accuracy: -5, criticalRate: 7, intelligence: 5),
			new ItemTemplate("Undead Hat", 38, ItemSlot.Helm, ItemParts.HatStereotype, accuracy: -4, criticalRate: 5, intelligence: 4),
			new ItemTemplate("Undead Crakows", 37, ItemSlot.Boots, ItemParts.CrakowsStereotype, accuracy: -3, criticalRate: 3, intelligence: 3),
			new ItemTemplate("Undead Mitts", 37, ItemSlot.Gloves, ItemParts.MittsStereotype, accuracy: -3, criticalRate: 3, intelligence: 3),
			new ItemTemplate("Beast Tunic", 38, ItemSlot.Chest, ItemParts.TunicStereotype, dexterity: 4, hp: 25),
			new ItemTemplate("Beast Hood", 37, ItemSlot.Helm, ItemParts.HoodStereotype, dexterity: 3, hp: 15),
			new ItemTemplate("Necro Robe", 36, ItemSlot.Chest, ItemParts.RobeStereotype),
			new ItemTemplate("Beast Boots", 36, ItemSlot.Boots, ItemParts.BootsStereotype, dexterity: 2, hp: 10),
			new ItemTemplate("Beast Gloves", 36, ItemSlot.Gloves, ItemParts.GlovesStereotype, dexterity: 2, hp: 10),
			new ItemTemplate("Necro Hat", 35, ItemSlot.Helm, ItemParts.HatStereotype),
			new ItemTemplate("Necro Crakows", 34, ItemSlot.Boots, ItemParts.CrakowsStereotype),
			new ItemTemplate("Necro Mitts", 34, ItemSlot.Gloves, ItemParts.MittsStereotype),
			new ItemTemplate("Necro Tunic", 33, ItemSlot.Chest, ItemParts.TunicStereotype),
			new ItemTemplate("Necro Hood", 32, ItemSlot.Helm, ItemParts.HoodStereotype),
			new ItemTemplate("Necro Boots", 31, ItemSlot.Boots, ItemParts.BootsStereotype),
			new ItemTemplate("Necro Gloves", 31, ItemSlot.Gloves, ItemParts.GlovesStereotype),
			new ItemTemplate("Overlord's Robe", 29, ItemSlot.Chest, ItemParts.RobeStereotype, accuracy: 5, intelligence: 4, hp: 25),
			new ItemTemplate("Ares' Gloves", 29, ItemSlot.Gloves, ItemParts.GlovesStereotype, strength: 2, dexterity: 2),
			new ItemTemplate("Gnoll Tunic", 29, ItemSlot.Chest, ItemParts.TunicStereotype, criticalRate: 5, dexterity: 3),
			new ItemTemplate("Shaman's Hat", 28, ItemSlot.Helm, ItemParts.HatStereotype, intelligence: 2, dexterity: 2),
			new ItemTemplate("Gnoll Hood", 28, ItemSlot.Helm, ItemParts.HoodStereotype, criticalRate: 4, dexterity: 2),
			new ItemTemplate("Gnoll Robe", 28, ItemSlot.Chest, ItemParts.RobeStereotype, intelligence: 3, hp: 15),
			new ItemTemplate("Gnoll Boots", 27, ItemSlot.Boots, ItemParts.BootsStereotype, criticalRate: 3, dexterity: 1),
			new ItemTemplate("Gnoll Gloves", 27, ItemSlot.Gloves, ItemParts.GlovesStereotype, criticalRate: 3, dexterity: 1),
			new ItemTemplate("Gnoll Hat", 28, ItemSlot.Helm, ItemParts.HatStereotype, intelligence: 2, hp: 12),
			new ItemTemplate("Worm Tunic", 27, ItemSlot.Chest, ItemParts.TunicStereotype, magicAttack: 5, accuracy: 5),
			new ItemTemplate("Gnoll Crakows", 26, ItemSlot.Boots, ItemParts.CrakowsStereotype, intelligence: 1, hp: 10),
			new ItemTemplate("Gnoll Mitts", 26, ItemSlot.Gloves, ItemParts.MittsStereotype, intelligence: 1, hp: 10),
			new ItemTemplate("Cashmere Robe", 26, ItemSlot.Chest, ItemParts.RobeStereotype),
			new ItemTemplate("Worm Hood", 26, ItemSlot.Helm, ItemParts.HoodStereotype, magicAttack: 4, accuracy: 4),
			new ItemTemplate("Worm Boots", 25, ItemSlot.Boots, ItemParts.BootsStereotype, magicAttack: 3, accuracy: 3),
			new ItemTemplate("Worm Gloves", 25, ItemSlot.Gloves, ItemParts.GlovesStereotype, magicAttack: 3, accuracy: 3),
			new ItemTemplate("Cashmere Hat", 25, ItemSlot.Helm, ItemParts.HatStereotype),
			new ItemTemplate("Cashmere Crakows", 24, ItemSlot.Boots, ItemParts.CrakowsStereotype),
			new ItemTemplate("Cashmere Mitts", 24, ItemSlot.Gloves, ItemParts.MittsStereotype),
			new ItemTemplate("Cashmere Tunic", 23, ItemSlot.Chest, ItemParts.TunicStereotype),
			new ItemTemplate("Cashmere Hood", 22, ItemSlot.Helm, ItemParts.HoodStereotype),
			new ItemTemplate("Cashmere Boots", 21, ItemSlot.Boots, ItemParts.BootsStereotype),
			new ItemTemplate("Cashmere Gloves", 21, ItemSlot.Gloves, ItemParts.GlovesStereotype),
			new ItemTemplate("Priest's Hat", 19, ItemSlot.Helm, ItemParts.HatStereotype, accuracy: 3, intelligence: 2),
			new ItemTemplate("Reinforced Tunic", 18, ItemSlot.Chest, ItemParts.TunicStereotype, defense: 5),
			new ItemTemplate("Lizard Tunic", 18, ItemSlot.Chest, ItemParts.TunicStereotype, strength: 2),
			new ItemTemplate("Leaping Boots", 18, ItemSlot.Boots, ItemParts.BootsStereotype, criticalRate: 3, dexterity: 2),
			new ItemTemplate("Murlok Robe", 17, ItemSlot.Chest, ItemParts.RobeStereotype, intelligence: 2),
			new ItemTemplate("Lizard Hood", 17, ItemSlot.Helm, ItemParts.HoodStereotype, attack: 5),
			new ItemTemplate("Deadly Boots", 17, ItemSlot.Boots, ItemParts.BootsStereotype, attack: 3, magicAttack: 3),
			new ItemTemplate("Deadly Gloves", 17, ItemSlot.Gloves, ItemParts.GlovesStereotype, attack: 3, magicAttack: 3),
			new ItemTemplate("Murlok Hat", 16, ItemSlot.Helm, ItemParts.HatStereotype, magicAttack: 5),
			new ItemTemplate("Murlok Boots", 16, ItemSlot.Boots, ItemParts.BootsStereotype, accuracy: 4),
			new ItemTemplate("Murlok Gloves", 16, ItemSlot.Gloves, ItemParts.GlovesStereotype, accuracy: 4),
			new ItemTemplate("Silk Robe", 16, ItemSlot.Chest, ItemParts.RobeStereotype),
			new ItemTemplate("Murlok Crakows", 15, ItemSlot.Boots, ItemParts.CrakowsStereotype, magicAttack: 4),
			new ItemTemplate("Murlok Mitts", 15, ItemSlot.Gloves, ItemParts.MittsStereotype, magicAttack: 4),
			new ItemTemplate("Silk Hat", 15, ItemSlot.Helm, ItemParts.HatStereotype),
			new ItemTemplate("Silk Crakows", 14, ItemSlot.Boots, ItemParts.CrakowsStereotype),
			new ItemTemplate("Silk Mitts", 14, ItemSlot.Gloves, ItemParts.MittsStereotype),
			new ItemTemplate("Silk Tunic", 13, ItemSlot.Chest, ItemParts.TunicStereotype),
			new ItemTemplate("Silk Hood", 12, ItemSlot.Helm, ItemParts.HoodStereotype),
			new ItemTemplate("Silk Boots", 11, ItemSlot.Boots, ItemParts.BootsStereotype),
			new ItemTemplate("Silk Gloves", 11, ItemSlot.Gloves, ItemParts.GlovesStereotype),
			new ItemTemplate("Gronok's Tunic", 9, ItemSlot.Chest, ItemParts.TunicStereotype, dexterity: 1, hp: 7),
			new ItemTemplate("Siru's Hat", 8, ItemSlot.Helm, ItemParts.HatStereotype, intelligence: 1),
			new ItemTemplate("Goblin Robe", 8, ItemSlot.Chest, ItemParts.RobeStereotype, magicAttack: 4),
			new ItemTemplate("Ranger Boots", 7, ItemSlot.Boots, ItemParts.BootsStereotype, criticalRate: 3),
			new ItemTemplate("Goblin Hat", 7, ItemSlot.Helm, ItemParts.HatStereotype, magicAttack: 3),
			new ItemTemplate("Scale Tunic", 7, ItemSlot.Chest, ItemParts.TunicStereotype, attack: 4),
			new ItemTemplate("Goblin Crakows", 6, ItemSlot.Boots, ItemParts.CrakowsStereotype, magicAttack: 2),
			new ItemTemplate("Goblin Mitts", 6, ItemSlot.Gloves, ItemParts.MittsStereotype, magicAttack: 2),
			new ItemTemplate("Scale Hood", 6, ItemSlot.Helm, ItemParts.HoodStereotype, attack: 3),
			new ItemTemplate("Spider Robe", 6, ItemSlot.Chest, ItemParts.RobeStereotype, accuracy: 4),
			new ItemTemplate("Hempen Robe", 6, ItemSlot.Chest, ItemParts.RobeStereotype),
			new ItemTemplate("Spider Hat", 5, ItemSlot.Helm, ItemParts.HatStereotype, accuracy: 3),
			new ItemTemplate("Hempen Hat", 5, ItemSlot.Helm, ItemParts.HatStereotype),
			new ItemTemplate("Spider Crakows", 4, ItemSlot.Boots, ItemParts.CrakowsStereotype, accuracy: 2),
			new ItemTemplate("Spider Mitts", 4, ItemSlot.Gloves, ItemParts.MittsStereotype, accuracy: 2),
			new ItemTemplate("Hempen Crakows", 4, ItemSlot.Boots, ItemParts.CrakowsStereotype),
			new ItemTemplate("Hempen Mitts", 4, ItemSlot.Gloves, ItemParts.MittsStereotype),
			new ItemTemplate("Hempen Tunic", 3, ItemSlot.Chest, ItemParts.TunicStereotype),
			new ItemTemplate("Hempen Hood", 2, ItemSlot.Helm, ItemParts.HoodStereotype),
			new ItemTemplate("Hempen Boots", 1, ItemSlot.Boots, ItemParts.BootsStereotype),
			new ItemTemplate("Hempen Gloves", 1, ItemSlot.Gloves, ItemParts.GlovesStereotype),
		};

		public static Item[] Trinkets = {
			new Item("Hel's Earring", 40, ItemSlot.Trinket, accuracy: 7, intelligence: 4),
			new Item("Oni's Earring", 40, ItemSlot.Trinket, criticalRate: 7, strength: 4),
			new Item("Kirin's Earring", 30, ItemSlot.Trinket, attack: 7, magicAttack: 7, accuracy: 7),
			new Item("Seastone Pendant", 20, ItemSlot.Trinket, magicAttack: 5, dexterity: 2),
			
			new Item("Skeletor's Ring", 39, ItemSlot.Trinket, attack: 15, accuracy: 15, hp: -10),
			new Item("Gnoll Ring", 25, ItemSlot.Trinket, dexterity: 2),
			new Item("Worm Ring", 22, ItemSlot.Trinket, intelligence: 2),
			new Item("Ram Ring", 22, ItemSlot.Trinket, strength: 2),
			new Item("Lizard Amulet", 12, ItemSlot.Trinket, criticalRate: 6),
			new Item("Turtle Ring", 12, ItemSlot.Trinket, magicDefense: 6),
			new Item("Grok's Amulet", 5, ItemSlot.Trinket, attack: 4),
			new Item("Arachne's Ring", 3, ItemSlot.Trinket, accuracy: 4),
		};
		
		public static Item[] Boosts = {
			new Item("Atk Boost", 10, ItemSlot.Boost, attack: 5),
			new Item("Matk Boost", 10, ItemSlot.Boost, magicAttack: 5),
			new Item("Acc Boost", 10, ItemSlot.Boost, accuracy: 5),
			new Item("Def Boost", 10, ItemSlot.Boost, defense: 1),
			new Item("Mdef Boost", 10, ItemSlot.Boost, magicDefense: 5),
			new Item("Str Boost", 30, ItemSlot.Boost, strength: 2),
			new Item("Int Boost", 30, ItemSlot.Boost, intelligence: 2),
			new Item("Dex Boost", 30, ItemSlot.Boost, dexterity: 2),
			new Item("Def Boost +1", 30, ItemSlot.Boost, defense: 15),
			new Item("Mdef Boost +1", 30, ItemSlot.Boost, magicDefense: 15),
		};

		public static Monster[] Monsters = {
			new Monster("Forest Gathering", 1, 0, 0, 0, 5, 5, 20),
			new Monster("Moss Golem", 2, 15, 5, 5, 10, 5, 40),
			new Monster("Forest Treant", 2, 5, 15, 5, 5, 10, 40),
			new Monster("Grass Spider", 3, 5, 20, 10, 5, 10, 50),
			new Monster("Arachne", 3, 5, 30, 15, 5, 10, 65),
			new Monster("Tuvale Viper", 4, 25, 5, 15, 10, 5, 60),
			new Monster("Venom", 4, 35, 10, 15, 10, 5, 70),
			new Monster("Wild Boar", 5, 20, 5, 5, 20, 5, 80),
			new Monster("Hogger", 5, 25, 5, 10, 30, 15, 100),
			new Monster("Goblin Footman", 6, 25, 5, 15, 25, 10, 100),
			new Monster("Grok The Mighty", 6, 35, 5, 20, 30, 10, 110),
			new Monster("Goblin Enchanter", 7, 5, 35, 10, 10, 15, 90),
			new Monster("Siru The Wise", 7, 5, 45, 10, 15, 25, 110),
			new Monster("Goblin Chieftain", 8, 40, 5, 20, 25, 15, 130),
			new Monster("Lord Gronok", 8, 50, 5, 25, 35, 15, 150),
			new Monster("Maexna", 9, 20, 40, 20, 20, 20, 250, maxPartyMembers: 2),
			new Monster("Queen Maexna", 9, 20, 55, 25, 20, 25, 280, maxPartyMembers: 2),
			new Monster("Yarsol Gathering", 10, 0, 0, 0, 10, 10, 70),
			new Monster("Coral Giant", 11, 30, 5, 15, 20, 20, 150),
			new Monster("Water Willow", 11, 5, 30, 15, 20, 20, 150),
			new Monster("Yarsol Snapper", 12, 20, 5, 10, 40, 30, 240),
			new Monster("Wild Turtle", 12, 30, 5, 15, 50, 35, 260),
			new Monster("Murlok Priest", 13, 10, 40, 30, 20, 20, 180),
			new Monster("Murlok Tidecaller", 13, 10, 50, 40, 20, 30, 200),
			new Monster("Sand Lizard", 14, 50, 5, 20, 30, 10, 200),
			new Monster("Leaping Lizzy", 14, 60, 5, 30, 40, 10, 220),
			new Monster("Murlok Spearman", 15, 50, 5, 30, 30, 10, 220),
			new Monster("Murlok Warleader", 15, 60, 5, 35, 35, 15, 240),
			new Monster("Murlok Assassin", 16, 55, 10, 50, 20, 10, 180),
			new Monster("Murlok Tidehunter", 16, 65, 10, 55, 30, 15, 190),
			new Monster("Murlok Highpriest", 17, 10, 70, 30, 20, 20, 220),
			new Monster("Prophet Nami", 17, 10, 80, 45, 25, 30, 250),
			new Monster("Basamus", 18, 110, 5, 30, 50, 30, 500, maxPartyMembers: 2),
			new Monster("Basamus Prime", 18, 130, 5, 30, 65, 35, 550, maxPartyMembers: 2),
			new Monster("Aldur Gathering", 20, 0, 0, 0, 20, 20, 150),
			new Monster("Highland Titan", 21, 50, 5, 30, 40, 20, 250),
			new Monster("Aldur Guardian", 21, 5, 50, 30, 30, 30, 250),
			new Monster("Aldur Ram", 22, 65, 5, 40, 50, 20, 270),
			new Monster("Ceros", 22, 75, 5, 50, 60, 20, 290),
			new Monster("Highland Tunneler", 23, 10, 75, 50, 40, 30, 250),
			new Monster("Terros", 23, 10, 85, 55, 50, 40, 280),
			new Monster("Gnoll Hunter", 24, 75, 5, 60, 55, 15, 300),
			new Monster("Reygar", 24, 90, 5, 60, 60, 20, 320),
			new Monster("Gnoll Shaman", 25, 5, 80, 50, 35, 35, 280),
			new Monster("Kaldar", 25, 5, 100, 60, 40, 40, 290),
			new Monster("Gnoll Overlord", 26, 150, 10, 70, 80, 40, 1000, maxPartyMembers: 3),
			new Monster("Drahgar", 26, 180, 10, 80, 100, 50, 1200, maxPartyMembers: 3),
			new Monster("Ares", 27, 190, 20, 80, 100, 60, 900, maxPartyMembers: 3),
			new Monster("Ares Prime", 27, 220, 30, 90, 130, 70, 1000, maxPartyMembers: 3),
			new Monster("Vulkrum Gathering", 30, 0, 0, 0, 25, 25, 200),
			new Monster("Dark Colossus", 31, 70, 5, 30, 50, 30, 320),
			new Monster("Haunted Harwood", 31, 5, 70, 30, 40, 40, 320),
			new Monster("Nightmare Scorpion", 32, 60, 80, 50, 100, 100, 750, maxPartyMembers: 2),
			new Monster("Scorpinox", 32, 80, 110, 60, 110, 110, 900, maxPartyMembers: 2),
			new Monster("Night Beast", 33, 150, 20, 70, 120, 70, 900, maxPartyMembers: 2),
			new Monster("Night Stalker", 33, 180, 40, 70, 150, 100, 1200, maxPartyMembers: 2),
			new Monster("Undead Warrior", 34, 250, 20, 100, 180, 100, 2500, maxPartyMembers: 3),
			new Monster("Skeletor", 34, 270, 20, 100, 200, 100, 2800, maxPartyMembers: 3),
			new Monster("Undead Mage", 35, 20, 300, 90, 90, 150, 2000, maxPartyMembers: 3),
			new Monster("Altor", 35, 20, 320, 100, 100, 170, 2100, maxPartyMembers: 3),
			new Monster("Antares", 36, 220, 220, 120, 180, 150, 3500, maxPartyMembers: 5),
			new Monster("Serket", 36, 250, 250, 120, 200, 160, 3800, maxPartyMembers: 5),
			new Monster("Lich King", 37, 400, 50, 120, 250, 120, 4000, maxPartyMembers: 5),
			new Monster("Arthus", 37, 440, 60, 120, 280, 140, 4500, maxPartyMembers: 5),
			new Monster("Leviathan", 20, 130, 140, 50, 100, 120, 2100, maxPartyMembers: 5),
			new Monster("Kirin", 30, 380, 140, 90, 260, 140, 2900, maxPartyMembers: 5),
			new Monster("Oni", 40, 450, 150, 120, 360, 200, 5400, maxPartyMembers: 6),
			new Monster("Hel", 40, 200, 540, 120, 180, 280, 4200, maxPartyMembers: 6),
		};
	}
}
